version: "3.9"

services:
  app:
    container_name: fastapi_template
    image: fastapi-template:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    volumes:
      - ./app:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "-X", "GET", "http://localhost:$$PORT/api/healthcheck" ]
      interval: 300s
      timeout: 180s
      retries: 5
